# Generated by Django 5.2 on 2025-05-13 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekandra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='offreemploi',
            name='date_fin',
            field=models.DateTimeField(default=' j/m/n '),
        ),
    ]
