# Generated by Django 5.2 on 2025-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekandra', '0002_alter_candidature_lettre_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='siret',
            field=models.CharField(max_length=14),
        ),
    ]
