# Generated by Django 5.2 on 2025-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekandra', '0003_alter_entreprise_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notation',
            name='note',
            field=models.IntegerField(choices=[(1, '1 Étoile'), (2, '2 Étoiles'), (3, '3 Étoiles'), (4, '4 Étoiles'), (5, '5 Étoiles')], default=0, help_text="Veuillez noter l'entreprise de 1 à 5 étoiles."),
        ),
    ]
