# Generated by Django 5.2 on 2025-05-31 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekandra', '0004_alter_notation_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notation',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
