# Generated by Django 5.2 on 2025-05-31 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ekandra', '0006_alter_candidature_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
